permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: Flaminsou
  description: |
    Flaminsou is an online shop that sell weird and one of a kind weapons to people who collect weapons for display purpose.
  font-url: "https://fonts.googleapis.com/css?family=Open+Sans|Philosopher"
  rationales:
    typefaces.primary: |
      Open Sans was selected because it is a typeface that is easy to read and clean. The typeface is only used for body copy and other stuffs.
    typefaces.secondary: |
      Philosopher is only to be used for title, headings, buttons, and banners.
