permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: Flaminsou
  description: |
    Flaminsou is an online shop that sell weird and one of a kind weapons to people who collect weapons for display purpose.
  font-url: "https://fonts.googleapis.com/css?family=Open+Sans|Philosopher"
  colors:
    background: "--color-neutral"
    accent: "--color-black"
  rationales:
    typefaces.primary: |
      Open Sans was selected because it is a typeface that is easy to read and clean. The typeface is only used for body copy.
    typefaces.secondary: |
      Philosopher was selected because the edge of the font are curved and that looks like a sword. It is only to be used for title, headings, buttons, and banners.
    colors.primary: |
      The primary colour represents the burning passion from the audience because they really want to buy weapons. Also, there are new weapons every week.
    colors.accent: |
      The accent colours are only used to hovering buttons and links.
    colors.neutral: |
      The neutral colour is only used for background.
