title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Basic buttons should be used inside card lists or checkout forms.
    fields:
      - name: text
        type: string
        example: "Buy Now"
      - name: text
        type: string
        example: "Add to Cart"
        required: false
      - name: url
        type: url
        example: "/products/"
        required: false
  ghost:
    title: "Ghost"
    description: |
      Ghost buttons should be used for banners only.
    fields:
      - name: text
        type: string
        example: "View Weapons"
      - name: url
        type: url
        example: "/products/"
        required: false
