title: "Cards List"
description: |
  The card list is for every weapon. It brings to the details page.

fields:
  - name: data
    type: object
    data:
      source: "site.products[0]"
      type: Product
