title: "Banner"
description: |
  Banners are only needed on the homepage.

patterns:
  banner:
    fields:
      - name: heading
        type: string
        example: "New Weapons"
      - name: text
        type: string
        example: "This week, we received 3 new kinds of weapon that are brought from Europe. They look amazing! Check them out!"
